---

- name: Test if distribution is RedHat
  assert:
    that: ansible_os_family == "RedHat" and
          ansible_distribution_major_version | int >= 6

- name: Install erlang and Rabbitmq
  yum:
    name: {{ item }}
    state: present
  with_items:
   - erlang
   - rabbitmq-server

# The better way to do this does not work yet
- name: Enable rabbitmq console
  command: 
    /usr/lib/rabbitmq/lib/rabbitmq_server-3.1.5/sbin/rabbitmq-plugins enable rabbitmq_management

- name: Make SSL dir
  file:
    path: "{{ rabbitmq_ssl_path }}"
    owner: "{{ rabbitmq_user }}"
    group: "{{ rabbitmq_group }}"
    mode: 0750
    state: directory

- name: Copy pem files to host
  copy: 
    src: "{{ item }}"
    dest: "{{ rabbitmq_ssl_path }}/{{ item }}"
    owner: "{{ rabbitmq_user }}"
    group: "{{ rabbitmq_group }}"
    mode: 0640
    backup: yes
  with_items:
   - "{{ rabbitmq_cacert }}"
   - "{{ rabbitmq_server_cert }}"
   - "{{ rabbitmq_server_key }}"
  notify: reload rabbitmq-server
  when: rabbitmq_ssl_self_signed_cert == false

- name: Setup rabbitmq.config for /etc/rabbitmq/
  template: 
    src: rabbitmq.conf.j2 
    dest: "{{ rabbitmq_conf_path }}/rabbitmq.config"
    owner: "{{ rabbitmq_user }}"
    group: "{{ rabbitmq_group }}"
    mode: 0640
    backup: yes

- name: Start Rabbitmq
  service:
    name: rabbitmq-server
    state: started
    enabled: true

- name: Add sensu vhost
  include: vhost.yaml
