---

- name: Test if distribution is RedHat
  assert:
    that: >
      ansible_os_family == "RedHat" and
      ansible_distribution_major_version | int >= 6

- name: Install rabbitmq-server
  yum:
    name: "{{ rabbitmq_pkg }}"

- name: Setup RabbitMQ config
  template:
    src: rabbitmq.conf.j2
    dest: /etc/rabbitmq/rabbitmq.config
  notify: Restart rabbitmq-server

- name: Make sure rabbitmq-server is enabled and running
  service:
    name: rabbitmq-server
    state: started
    enabled: true
