---

- name: Test distribution
  assert:
    that: ansible_os_family == "RedHat"

- name: copy custom repo files to host
  copy: 
    src=epel.repo 
    dest="{{yum_repo_dir}}" 
    owner=root group=root mode=644
  copy: 
    src=sensu.repo 
    dest="{{yum_repo_dir}}" 
    owner=root group=root mode=644

- name: install erlang and rabbitmq
  yum: name={{ item }} state=present
  with_items:
   - erlang
   - rabbitmq-server

- name: enable rabbitmq console
  shell: 
    /usr/lib/rabbitmq/lib/rabbitmq_server-3.1.5/sbin/rabbitmq-plugins enable rabbitmq_management

- name: make ssl dir
  command: mkdir -p /etc/rabbitmq/ssl

- name: copy pem files to host
  copy: 
    src=server_key.pem 
    dest={{rabbitmq_ssl_dir}} 
    owner=root group=root mode=644
  copy: 
    src=server_cert.pem 
    dest={{rabbitmq_ssl_dir}} 
    owner=root group=root mode=644
  copy: 
    src=cacert.pem 
    dest={{rabbitmq_ssl_dir}} 
    owner=root group=root mode=644

- name: setup rabbitmq.conf for /etc/rabbitmq/
  template: 
    src=rabbitmq.conf.j2 
    dest=/etc/rabbitmq/rabbitmq.conf

- name: startup rabbitmq
  command: 
    /sbin/chkconfig rabbitmq-server on
  command: 
    /etc/init.d/rabbitmq-server start

- name: set rabbitmq with sensu user and credentials
  shell: 
    rabbitmqctl add_vhost /sensu
## To fix below
#  shell: 
#    rabbitmqctl add_user sensu mypass
#  shell: 
#    rabbitmqctl set_permission -p /sensu sensu ".*" ".*" ".*"
