---

- name: Test if distribution is RedHat
  assert:
    that: ansible_os_family == "RedHat" and
          ansible_distribution_major_version | int >= 6

- name: DEBUG install
  debug: msg="Rabbitmq repo {{ rabbitmq_repo_url }}"

- name: Install Rabbitmq 
  yum:
    name: rabbitmq-server
    state: latest

- name: Enable rabbitmq plugins
  rabbitmq_plugin:
    names: "{{ rabbitmq_plugins }}"
    state: enabled

- name: Setup rabbitmq.config for /etc/rabbitmq/
  template: 
    src: rabbitmq.conf.j2 
    dest: "{{ rabbitmq_conf_path }}/rabbitmq.config"
    owner: "{{ rabbitmq_user }}"
    group: "{{ rabbitmq_group }}"
    mode: 0640
    backup: yes
  notify:
    reload_rabbitmq_server

- name: Start Rabbitmq
  service:
    name: rabbitmq-server
    state: started
    enabled: true

- name: Add sensu vhost
  include: vhost.yaml
